name: 'telegrahm_dbt'
version: '1.0.0'
config-version: 2

profile: 'telegrahm_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  telegrahm_dbt:
    # Base configuration applied to all models
    +materialized: view
    +schema: "telegram_dbt"  # Base schema name
    
    # Staging models configuration
    staging:
      +materialized: view
      +schema: "{{ target.schema }}_staging"  # Will become telegram_dbt_staging
      
    # Marts models configuration  
    marts:
      +materialized: table
      +schema: "{{ target.schema }}_marts"    # Will become telegram_dbt_marts